#!/bin/bash

git checkout develop
git pull

echo -e "${YELLOW}Select the type of branch you want to create:"
echo -e "1) feature"
echo -e "2) fix"
echo -e "3) hotfix"
echo -e "4) enhancement"
read -p "Enter your choice (1-4): " choice

case $choice in
    1) branch_type="feature";;
    2) branch_type="fix";;
    3) branch_type="hotfix";;
    4) branch_type="enhancement";;
    5) branch_type="docs";;
    *) echo -e "Invalid choice"; exit 1;;
esac

read -p "Enter the branch description: " description
branch_name="${branch_type}/$(echo $description | tr ' ' '-')"

git checkout -b $branch_name
